name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  WORKING_DIRECTORY: ./src

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
    - uses: actions/checkout@v2
    - uses: extractions/setup-just@v1

    - name: Configure AWS Credentials
      run: | 
        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY }}"
        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_KEY }}"
        export AWS_REGION="eu-west-1"
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_KEY }}
        
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Lint
      id: lint
      if: github.event_name == 'pull_request'
      run: just lint

    - name: Build backend
      id: build-backend
      run: |
        just build-backend profiles
      
    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: terraform plan -no-color

    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve

    - name: Deploy Client
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        sudo apt-get install jq
        # CLIENT_BUCKET=$(echo ${{ steps.apply.outputs }} | jq -r '.client_bucket')
        CLIENT_BUCKET=suppdev-client
        just deploy-client $CLIENT_BUCKET
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_REGION: eu-west-1
